const WORD_BANK = {
  nature:["THUNDERSTORM","WILDERNESS","WATERFALL","EVERGREEN","SUNFLOWER","BUTTERFLY","GRASSLAND","BLUEBERRY","RASPBERRY","SNOWFLAKE","RAINFOREST","DRAGONFLY","PINECONE","HEDGEHOG","PORCUPINE","BLACKBIRD","WHIRLPOOL","TREELINE","CLOUDBANK","SHORELINE","DRIFTWOOD","EARTHWORM","MARSHLAND","STARLIGHT","SALTWATER","FOXGLOVE","SANDSTONE"],
  canadian:["PARLIAMENT","LAKESHORE","PROVINCES","TERRITORY","WILDERNESS","TUNDRA","CARIBOU","SNOWMOBILE","LUMBERJACK","TOBOGGANING","CANOEIST","PRAIRIES","BLACKBERRY","BLUEBERRY","PERMAFROST","PORTAGE","FIREWOOD","SNOWDRIFT","TRAPPER","STAMPEDE","PIPELINE","HINTERLAND","ARROWHEAD","BIRCHBARK","WHITEWATER"],
  food:["BREADCRUMB","PEPPERCORN","BUTTERSCOTCH","ARTICHOKE","GINGERBREAD","STRAWBERRY","BLACKBERRY","BLUEBERRY","MARMALADE","SHORTBREAD","CORNSTARCH","CHEESECAKE","BUTTERMILK","SOURDOUGH","WATERMELON","PINEAPPLE","CHOCOLATE","SPEARMINT","ROSEMARY","TANGERINE","ELDERBERRY","BUTTERNUT","PERSIMMON","GRAPEFRUIT","CARDAMOM","SUNFLOWER","CORNBREAD","APPLESAUCE"],
  sports:["TOUCHDOWN","GOALKEEPER","WRESTLING","SPRINGBOARD","BACKSTROKE","FOREHAND","MARATHON","BASKETBALL","VOLLEYBALL","SKATEBOARD","SNOWBOARD","LACROSSE","SCOREBOARD","UNDERHAND","CROSSBAR","SPRINTER","HALFPIPE","OVERTIME","SIDELINE","PLAYMAKER","GOALPOST","DROPKICK","LEFTHOOK","UPPERCUT"],
  farming:["FARMSTEAD","LIVESTOCK","HAYSTACK","PITCHFORK","CORNFIELD","SCARECROW","THRESHING","POLLINATE","HARVESTER","WINDMILL","SHEEPDOG","GREENHOUSE","SEEDLING","BARNYARD","IRRIGATION","PLOWSHARE","ORCHARD","COMPOST","BEEKEEPER","HENHOUSE","CATTLEMAN","SUNFLOWER","FARMHOUSE","HAYMAKER","CROPLAND","SHEPHERD","CULTIVATOR"],
  trades:["BLACKSMITH","STEELWORK","FRAMEWORK","BLUEPRINT","CARPENTER","IRONWORKS","SCAFFOLDING","FOUNDATION","BRICKWORK","WORKBENCH","IRONCLAD","METALWORK","MILLWRIGHT","PIPEFITTER","SPARKPLUG","CRANKSHAFT","DRIVESHAFT","FLYWHEEL","TOOLMAKER","SLEDGEHAMMER","GRINDSTONE","SANDPAPER","TINSMITH","COPPERWORK","STEELPLATE","WORKSHOP","IRONFORGE"],
  outdoors:["CAMPGROUND","BACKPACKER","TRAILHEAD","STARGAZER","RIVERBANK","MOUNTAINTOP","PATHFINDER","TREEHOUSE","HAMMOCK","KAYAKING","TRAILBLAZER","LAKESHORE","RAPPELLING","GLAMPING","OVERLANDER","BUSHCRAFT","WAYFINDER","CAMPSITE","BASECAMP","WOODCRAFT","SNOWSHOEING","CLIFFSIDE","RIDGELINE","WILDERNESS","FLATWATER","DOWNRIVER","SCOUTING"],
  general:["THUNDERCLAP","ADVENTURE","KNOWLEDGE","REMARKABLE","CROSSWORD","DISCOVERY","WONDERFUL","CHALLENGE","FANTASTIC","YESTERDAY","SOMETHING","BEAUTIFUL","BREAKFAST","CARPENTER","DANGEROUS","AFTERNOON","EVERYBODY","FORGOTTEN","GRANDFATHER","IMAGINATION","JELLYFISH","NIGHTMARE","OVERBOARD","PASSENGER","QUICKSAND","SHIPWRECK","TRANSFORM","WAREHOUSE","BIRTHPLACE","UNDERSTAND"]
};
const THEMES={
  nature:{name:"Nature Week",color:"#4ae89a",emoji:"🌿",desc:"Words from the natural world"},
  canadian:{name:"Canada Week",color:"#e84a4a",emoji:"🍁",desc:"Proudly Canadian words"},
  food:{name:"Food Week",color:"#e8c84a",emoji:"🍞",desc:"From kitchen to table"},
  sports:{name:"Sports Week",color:"#4a9ae8",emoji:"⚡",desc:"Get in the game"},
  farming:{name:"Farm Week",color:"#a0e84a",emoji:"🌾",desc:"From the land"},
  trades:{name:"Trades Week",color:"#e8844a",emoji:"🔧",desc:"Built with skill"},
  outdoors:{name:"Outdoors Week",color:"#4ae8d8",emoji:"⛺",desc:"Wild and free"},
  general:{name:"Word Fest",color:"#c84ae8",emoji:"✨",desc:"The best of everything"}
};
const THEME_ORDER=["trades","nature","food","sports","farming","canadian","outdoors","general"];
function getTodayTheme(){const s=new Date("2024-01-01"),n=new Date(),w=Math.floor((n-s)/(7*24*60*60*1000));return THEME_ORDER[w%THEME_ORDER.length];}
function getTodayWord(){const t=getTodayTheme(),words=WORD_BANK[t],d=new Date(),dy=Math.floor((d-new Date(d.getFullYear(),0,0))/(864e5)),seed=d.getFullYear()*1000+dy;return words[seed%words.length].replace(/\s/g,"");}
function getTodayDateStr(){return new Date().toLocaleDateString("en-CA",{weekday:"long",year:"numeric",month:"long",day:"numeric"});}
function getDayNumber(){return Math.floor((new Date()-new Date("2024-01-01"))/(864e5));}
